# Generated by Django 4.2.26 on 2025-11-28 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botmessage',
            name='message_type',
            field=models.CharField(choices=[('start', 'Стартовое сообщение'), ('about', 'О нас'), ('courses', 'Курсы'), ('contact', 'Связаться с нами'), ('location', 'Как нас найти'), ('aml', 'AML Проверка'), ('cityex24_question', 'Cityex24 - Вопрос о стране'), ('cityex24_confirmation', 'Cityex24 - Подтверждение заявки')], max_length=30, unique=True, verbose_name='Тип сообщения'),
        ),
        migrations.CreateModel(
            name='Cityex24Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('kyrgyzstan', '🇰🇬 Кыргызстан'), ('uzbekistan', '🇺🇿 Узбекистан'), ('uae', '🇦🇪 ОАЭ'), ('turkey', '🇹🇷 Турция'), ('saudi_arabia', '🇸🇦 Саудовская Аравия')], max_length=20, verbose_name='Страна')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В обработке'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Заметки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cityex24_transfers', to='bot.telegramuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заявка Cityex24',
                'verbose_name_plural': 'Заявки Cityex24',
                'ordering': ['-created_at'],
            },
        ),
    ]
