# Generated by Django 4.2.26 on 2025-11-28 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_adminchat'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityex24transfer',
            name='contact_first_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя контакта'),
        ),
        migrations.AddField(
            model_name='cityex24transfer',
            name='contact_last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия контакта'),
        ),
        migrations.AddField(
            model_name='cityex24transfer',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='botmessage',
            name='message_type',
            field=models.CharField(choices=[('start', 'Стартовое сообщение'), ('about', 'О нас'), ('courses', 'Курсы'), ('contact', 'Связаться с нами'), ('location', 'Как нас найти'), ('aml', 'AML Проверка'), ('cityex24_question', 'Cityex24 - Вопрос о стране'), ('cityex24_contact_request', 'Cityex24 - Запрос контакта'), ('cityex24_confirmation', 'Cityex24 - Подтверждение заявки')], max_length=30, unique=True, verbose_name='Тип сообщения'),
        ),
    ]
