# Generated by Django 4.2.26 on 2025-11-29 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_cityex24transfer_contact_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('buy', 'Покупка'), ('sell', 'Продажа')], max_length=10, verbose_name='Тип транзакции')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма')),
                ('currency_from', models.CharField(default='USDT', max_length=10, verbose_name='Валюта от')),
                ('currency_to', models.CharField(default='RUB', max_length=10, verbose_name='Валюта к')),
                ('exchange_rate', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Курс обмена')),
                ('full_name', models.CharField(max_length=255, verbose_name='Ф.И.О')),
                ('wallet_address', models.CharField(max_length=255, verbose_name='Адрес кошелька')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В обработке'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Заметки')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='bot.telegramuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма')),
                ('currency', models.CharField(default='RUB', max_length=10, verbose_name='Валюта')),
                ('recipient_name', models.CharField(max_length=255, verbose_name='Получатель')),
                ('recipient_details', models.TextField(verbose_name='Детали получателя')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В обработке'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Заметки')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='bot.telegramuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Выплата',
                'verbose_name_plural': 'Выплаты',
                'ordering': ['-created_at'],
            },
        ),
    ]
