# Generated by Django 4.2.26 on 2025-11-30 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_transaction_payout'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.BigIntegerField(verbose_name='Telegram User ID')),
                ('order_type', models.CharField(choices=[('buy', 'Покупка'), ('sell', 'Продажа')], max_length=10, verbose_name='Тип заявки')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Сумма')),
                ('exchange_rate', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Курс обмена')),
                ('amount_to_receive', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Сумма к получению')),
                ('full_name', models.CharField(max_length=255, verbose_name='Ф.И.О')),
                ('wallet_address', models.CharField(max_length=255, verbose_name='Адрес кошелька')),
                ('status', models.CharField(choices=[('pending', 'Ожидание'), ('processed', 'Обработано'), ('cancelled', 'Отменено')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Заметки')),
            ],
            options={
                'verbose_name': 'Заявка на обмен',
                'verbose_name_plural': 'Заявки на обмен',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
        migrations.DeleteModel(
            name='Payout',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
