# Generated by Django 4.2.26 on 2025-11-30 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_exchangeorder_remove_transaction_user_delete_payout_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangeorder',
            name='telegram_user_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Telegram User ID'),
        ),
    ]
