# Generated by Django 4.2.26 on 2025-12-01 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_alter_exchangeorder_telegram_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cityex24transfer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cityex24_transfers', to='bot.telegramuser', verbose_name='Пользователь'),
        ),
    ]
