# Generated by Django 4.2.26 on 2025-12-04 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_alter_cityex24transfer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botmessage',
            name='message_type',
            field=models.CharField(choices=[('start', 'Стартовое сообщение'), ('about', 'О нас'), ('support', 'Поддержка'), ('courses', 'Курсы'), ('contact', 'Связаться с нами'), ('location', 'Как нас найти'), ('aml', 'AML Проверка'), ('cityex24_question', 'Cityex24 - Вопрос о стране'), ('cityex24_contact_request', 'Cityex24 - Запрос контакта'), ('cityex24_confirmation', 'Cityex24 - Подтверждение заявки')], max_length=30, unique=True, verbose_name='Тип сообщения'),
        ),
    ]
